client_config_backend: settings
client_config:
  client_id: 452398705183-7o8in94k8u82j71hllgfa3q9opvit5a0.apps.googleusercontent.com
  client_secret: EMMJJEajLTYTP2KYfac9Gmsl

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install